### ISSUE TITLE
Please Create one for Mojave and Catalina

### ISSUE THREAD

**Issue by comccoy** [jamf/CIS-for-macOS-High-Sierra#4]
I have several Mac build techs who would love to participate in getting this up to date for the newer OSes but we would rather participate in an overall community effort than just keep it all in house.

**Comment by erinmc** [comment]
Hi comccoy,

Thanks much for the offer and request.  As of this time, CIS has not released the benchmarks for Mojave and Catalina beyond a draft that is definitely going to change.  Once these have been published we can start building the benchmarks for 10.14 and 10.15

**Comment by comccoy** [comment]
No chance of having a "development" or "Beta" available for customers to start evaluating and/or contributing? We can fork the existing and do our own but would rather work off an actual 10.14/10.15 "official" location.

**Comment by dblundell** [comment]
CIS has released the benchmarks for Mojave and Catalina at https://www.cisecurity.org/cis-benchmarks
